routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboards.index');
    //return view('welcome');
});


Route::get('/table',function(){
    return view('tables.table');
});

Route::get('/data-table',function(){
    return view('tables.datatables');
});

/**
 * route all for cast
 */
/* Route::get('/cast','castcontroller@index');
Route::get('/cast/create','castcontroller@create');
Route::post('/store','castcontroller@store');
Route::get('/casts/{id}','castcontroller@show');
Route::get('/casts/{id}/edit','castcontroller@edit');
Route::put('/store/{id}','castcontroller@update');
Route::delete('/cast/{id}','castcontroller@destroy'); */
Route::resource('Cast','CastController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Cast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    //

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Cast;
class CastController extends Controller
{
    public function __construct(){
        $this->middleware('auth')->except(['index']);
    }
    /**
     * method index
     */
    public function index(){
        // use Query builder
        //$dataCasts = DB::table('casts')->get();
        // use ORM Elequent (model)
        $dataCasts = Cast::all();
        //dd($dataCasts);
        return view('cast.index',['casts'=>$dataCasts]);
    }
    /**
     * method get create
     * description : show form create post
     */

     public function create(){

        return view('cast.create');
     }

     /*
     * method post
     * description for insert to database
     *   */
    public function store(Request $request){

        $validated = $request->validate([
            'nama' => 'required|unique:casts|max:255',
            'umur' => 'required',
            'bio' => 'required',
        ]);
        /* $postForm = [
            'nama'  => $request['nama'],
            'umur'  => $request['umur'],
            'bio'  => $request['bio'],
            'created_at' => date('Y-m-d H:i:s')
        ]; */

        // create object entity casts
        $cast = new Cast;
        $cast->nama = $request['nama'];
        $cast->umur = $request['umur'];
        $cast->bio = $request['bio'];
        $cast->created_at = date('Y-m-d H:i:s');
        $cast->save();
        //$insert = DB::table('casts')->insert($postForm);

        return redirect('/Cast')->with('success','Data Cast Berhasil Disimpan!');
    }

    public function show($id){
        // use query builder
        //$castById = DB::table('casts')->where('id',$id)->first();
        //dd($castById);
        // use elequent
        $castById = Cast::find($id);
        return view('cast.show',compact('castById'));
    }

    public function edit($id){
        // use query builder
        //$castById = DB::table('casts')->where('id',$id)->first();
        //dd($castById);
        // use elequent
        $castById = Cast::find($id);
        return view('cast.edit',compact('castById'));
    }

    public function update($id, Request $request){
        $validated = $request->validate([
            'umur' => 'required',
            'bio' => 'required',
        ]);
        // use query builder
       /*  $postFormUpdate = [
            'nama'  => $request['nama'],
            'umur'  => $request['umur'],
            'bio'  => $request['bio'],
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $update = DB::table('casts')
                    ->where('id',$id)
                    ->update($postFormUpdate); */

        //dd($castById);
        // use elequent model
        $postFormUpdate = [
            'nama'  => $request['nama'],
            'umur'  => $request['umur'],
            'bio'  => $request['bio'],
            'updated_at' => date('Y-m-d H:i:s')
        ];
        $update = Cast::where('id', $id)->update(
            $postFormUpdate
        );
        return redirect('/Cast')->with('success','Data Cast Berhasil Dirubah!');

    }

    public function destroy($id){
        // use query builder
        /*  $delete = DB::table('casts')->where('id',$id)->delete(); */
        Cast::destroy($id);
         return redirect('/Cast')->with('success','Data Cast Berhasil Dihapus!');

    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/cast/create.blade.php
@extends('layout.master')
@section('title','Cast Create Page')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">  Form Cast </h1>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            Create
                        </div>
                        <div class="card-body">
                            <form role="form" action="{{ route('Cast.store')}}" method="post">
                                @csrf
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="nama">Nama</label>
                                        <input type="text" class="form-control" id="nama" name="nama" value="{{ old('nama','')}}"
                                        placeholder="Enter Nama">
                                        @error('nama')
                                            <div class="alert alert-danger"> {{$message}}</div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="umur">Umur</label>
                                        <input type="number" class="form-control" id="umur" name="umur" value="{{ old('umur','')}}"
                                        placeholder="Enter Umur">
                                         @error('umur')
                                            <div class="alert alert-danger"> {{$message}}</div>
                                        @enderror
                                    </div>
                                     <div class="form-group">
                                        <label for="bio">Bio</label>
                                        <textarea name="bio" id="bio" name="bio" cols="30" rows="10" class="form-control" value="{{ old('bio','')}}"></textarea>
                                         @error('nama')
                                            <div class="alert alert-danger"> {{$message}}</div>
                                        @enderror
                                    </div>

                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href={{Route('Cast.index')}} class="btn btn-dark">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cast/edit.blade.php
@extends('layout.master')
@section('title','Edit')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">  Form Cast Edit</h1>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            Create
                        </div>
                        <div class="card-body">
                            <form role="form" action="/Cast/{{$castById->id}}"
                                method="post">
                                @csrf
                                @method('PUT')
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="nama">Nama</label>
                                        <input type="text" class="form-control" id="nama" name="nama" value="{{ old('nama', $castById->nama)}}"
                                        placeholder="Enter Nama">
                                        @error('nama')
                                            <div class="alert alert-danger"> {{$message}}</div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="umur">Umur</label>
                                        <input type="text" class="form-control" id="umur" name="umur" value="{{ old('umur', $castById->umur)}}"
                                        placeholder="Enter Umur">
                                         @error('umur')
                                            <div class="alert alert-danger"> {{$message}}</div>
                                        @enderror
                                    </div>
                                     <div class="form-group">
                                        <label for="bio">Bio</label>
                                        <textarea name="bio" id="bio" name="bio" cols="30" rows="10" class="form-control" value="{{ old('bio',$castById->bio)}}"> {{old('bio',$castById->bio)}}</textarea>
                                         @error('nama')
                                            <div class="alert alert-danger"> {{$message}}</div>
                                        @enderror
                                    </div>

                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href={{Route('Cast.index')}} class="btn btn-dark">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cast/index.blade.php
@extends('layout.master')
@section('title','Cast Index Page')
@section('content')
 <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Cast</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Cast</li>
                    </ol>
                </div><!-- /.col -->
            </div>
        </div>
    </div>
 <!-- End Content Header (Page header) -->
 <!-- Main content -->
 <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        List Of Cast
                    </div>
                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{session('success')}}
                            </div>
                        @endif
                        <a href={{Route('Cast.create')}} class="btn btn-info mb-3"><i class="fa fa-plus"> Create</i></a>
                        <table id="cast-table" class="table table-bordered table table-striped ">
                            <thead>
                                <tr>
                                    <th>NO</th>
                                    <th>NAMA</th>
                                    <th>UMUR</th>
                                    <th>BIO</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               @foreach ($casts as $cast)
                                   <tr>
                                       <td>{{ $loop->iteration }}</td>
                                       <td> {{ $cast->nama}}</td>
                                       <td> {{ $cast->umur}}</td>
                                       <td> {{ $cast->bio}}</td>
                                       <td style="display:flex">
                                            <a href=" {{route('Cast.show',['Cast' => $cast->id])}} " class="btn btn-info mr-2"> show</a>
                                            <a href=" {{route('Cast.show',['Cast' => $cast->id])}}/edit" class="btn btn-success mr-2"> Edit</a>
                                            <form action="{{route('Cast.destroy',['Cast' => $cast->id])}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <input type="submit" value="Delete" class="btn btn-danger"/>
                                            </form>
                                        </th>
                                   </tr>
                               @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
 </section>
@endsection

resources/views/cast/show.blade.php
@extends('layout.master')
@section('title','Show Detail ')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Show Cast Detail</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Cast Detail</li>
                    </ol>
                </div><!-- /.col -->
            </div>
        </div>
    </div>
 <!-- End Content Header (Page header) -->
 <!-- Main content -->
 <section class="content">
    <div class="container-fluid">
        <div class="row">
           <div class="col-lg-12">
               <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Cast Show By Id {{$castById->id}}</h3>

            </div>
              <!-- /.card-header -->
              <div class="card-body">
                  <div class="col-md-3">
                        <a href={{route('Cast.index')}} class="btn btn-success">  Back</a>
                    </div>
                  <h1> Nama : {{$castById->nama}}</h1>
                  <h1> Umur : {{$castById->umur}}</h1>
                  <h4> Bio : {{$castById->umur}}</p>
              </div>
            </div>
           </div>
        </div>
    </div>
 </section>
@endsection

resources/views/dashboards/index.blade.php
@extends('layout.master')
@section('title','Dashboard')
@section('content')
   <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
           <div class="row">
                <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                <div class="inner">
                    <h3>150</h3>

                    <p>New Orders</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
          </div>
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                <div class="inner">
                    <h3>53<sup style="font-size: 20px">%</sup></h3>

                    <p>Bounce Rate</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>44</h3>

                <p>User Registrations</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>65</h3>

                <p>Unique Visitors</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
           </div>
        </div>
    </section>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> App-Page - @yield('title')</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href={{asset('/template-adminlte/plugins/fontawesome-free/css/all.min.css')}}>
  <!-- Theme style -->
  <link rel="stylesheet" href={{asset('/template-adminlte/dist/css/adminlte.min.css')}}>
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <!-- Navbar-->
  @include('layout.navbar')

  <!-- Sidebar -->
  @include('layout.menu')


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src={{asset('/template-adminlte/plugins/jquery/jquery.min.js')}}></script>
<!-- Bootstrap 4 -->
<script src={{asset('/template-adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}></script>
<!-- AdminLTE App -->
<script src={{'/template-adminlte/dist/js/adminlte.min.js'}}></script>
<!-- AdminLTE for demo purposes -->
<script src={{'/template-adminlte/dist/js/demo.js'}}></script>
<!-- stack link datatables -->
<script src="/template-adminlte/plugins/datatables/jquery.dataTables.js"></script>
<script src="/template-adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
</body>
</html>

resources/views/layout/menu.blade.php
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
      <img src={{asset('/template-adminlte/dist/img/AdminLTELogo.png')}} alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">For Admin Movie</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src={{asset('/template-adminlte/dist/img/user2-160x160.jpg')}} class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{Auth::user()}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="../../index.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v1</p>
                </a>
              </li>

            </ul>
          </li>

          <li class="nav-item">
            <a href="" class="nav-link">
              <i class="nav-icon fas fa-table"></i>
              <p>
                Tables
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href={{url('table')}} class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Simple Tables</p>
                </a>
              </li>
              <li class="nav-item">
                <a href={{url('data-table')}} class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>DataTables</p>
                </a>
              </li>

            </ul>
          </li>

           <li class="nav-item">
            <a href="" class="nav-link">
              <i class="nav-icon fas fa-user"></i>
              <p>
                Cast
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href={{ route('Cast.index')}} class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Cast</p>
                </a>
              </li>
            </ul>
          </li>


        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>